### ISSUE TITLE
[Bug] Values not supported by TimePicker Widget

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#67]
Some values aren't supported by the TimePicker widget. Sometimes it's because there are mistakes, sometimes it's because the widget didn't recognize the syntax (like in the screenshot below).

I think a text mode option could be interesting with the widget => for error correction, or to modify non supported values.

![screenshot_2016-10-04-08-12-03_cr](https://cloud.githubusercontent.com/assets/21213907/19104091/e5172626-8ada-11e6-8fb3-3d303e95ea2d.png)

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2
**Version:**
3.0.0 + "Preset par défaut" profile + expert mode

**Comment by loicortola** [comment]
This has been fixed in 3.0.1. @GilBr could you confirm all is good and resolved?

**Comment by GilBr** [comment]
Hum it seems it's not really fixed.
I still have the same behaviour with the 3.0.2 version with several POI.
Like this [one](https://www.openstreetmap.org/node/3181860670) with this kind of value : Tu-Fr 11:00-15:00,**17:00+**; Sa **17:00+**
Or this [one](https://www.openstreetmap.org/node/4323494490) with : Mo-Fr 12:00-14:00,19:30-22:00; **Jul off**
